name: Restart AnieXEricaMusic

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Match the version in your `runtime.txt` or preferred version

    - name: Install system dependencies (ffmpeg, Node.js)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start the app
      run: |
        python3 -m AnieXEricaMusic
